events:
  - _tag: SystemPrompt
    content: |-
      You are a helpful, friendly assistant.
      Keep your responses concise but informative.
      Use markdown formatting when helpful.
  - _tag: UserMessage
    content: "Say exactly: HELLO"
  - _tag: AssistantMessage
    content: HELLO
  - _tag: UserMessage
    content: "Say exactly: HELLO"
  - _tag: AssistantMessage
    content: HELLO
  - _tag: UserMessage
    content: "Say exactly: HELLO"
  - _tag: AssistantMessage
    content: HELLO
