events:
  - _tag: SystemPrompt
    content: |-
      You are a helpful, friendly assistant.
      Keep your responses concise but informative.
      Use markdown formatting when helpful.
  - _tag: UserMessage
    content: hello
  - _tag: AssistantMessage
    content: Hello! How can I assist you today?
  - _tag: UserMessage
    content: hello
  - _tag: AssistantMessage
    content: Hi again! How can I help you?
